### ISSUE TITLE
Doesn't work very well on https://github.com/SPBTV/video_av1_samples/blob/master/spbtv_sample_bipbop_av1_960x540_25fps.mp4

### ISSUE THREAD

**Issue by jrmuizel** [mdakram28/media-parser-gui#1]
I get a bunch of `reserved_obu(): Not implemented` errors

**Comment by mdakram28** [comment]
The AV1 parser expects a raw AV1 bitstream. MP4 is a container for media streams.

Use this command to extract the AV1 raw bitstream from the MP4 file using ffmpeg:
```bash
ffmpeg -i my/input/video.mp4 -c:v copy -copy_unknown bitstream.obu
```
